[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run --chip STM32F429ZITx"
runner = "probe-rs-cli run --chip STM32F429ZITx"
rustflags = ["-C", "codegen-units=1"]
[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
